### PR TITLE
Finished web mock-up

### PR DESCRIPTION
**Pull request by ikayz**
I worked on the design and some parts need further coding and/or improvements but for now. Have a look at it. I used some CSS from the previous contributor, it is partially responsive I had trouble in that area. The checkmark section I was not so clear. Please let me know what I should change and what you think.

### CODE REVIEW

**Comment by yochannah** [comment]
@ikayz Hey, this looks really great! I like the blue and red theming. 

The only real change I'd like would be to move the inline styling out of the html and into css classes instead. Are you ok with doing that? Let me know if it might be a problem :)

**Comment by ikayz** [comment]
@yochannah Hi, thanks! I have made the requested changes. For anything else just let me know. I'll gladly work on it.

**Review by yochannah — APPROVED** [review]
@ikayz Nice one! Thank you so much for this - I'll merge now. If you'd like me to send over some code is science stickers, email me your postal address to yochannah@gmail.com and I'll send them over <3

**Comment by ikayz** [comment]
@yochannah I'll email you my address, thanks.

**Pull request merged**
