### PR TITLE
Added icons to nav links

### PR DESCRIPTION
**Pull request by ikayz**
icons
icons1

Links to relevant issues/docs#

## What does this PR do?
Addition of icons as requested.

* Added symbol definitions to symbol-defs.svg
* Placed links in nav bar using journal_table.html file.

### CODE REVIEW

**Comment by ikayz** [comment]
@yochannah please check and review my changes if I have done them correctly, let me know if I need to make more changes

**Comment by yochannah** [comment]
@ikayz Great start, but a couple of changes needed here - 

1. the "use HTML" bit from icomoon needs to be added to the links in the [header partial](https://github.com/yochannah/code-is-science/blob/6a764f74d3d05fe53aa62905585650083f3625ca/themes/codeisscience/layouts/partials/header.html#L24-L26):  - you can see a similar example [here](https://raw.githubusercontent.com/yochannah/code-is-science/master/content/contact.md)
2. the icon css isn't actually needed this time - but if it was, it should go into the [less](https://github.com/yochannah/code-is-science/blob/master/themes/codeisscience/static/css/style.less) file. You can read a little bit more about it here: https://github.com/yochannah/code-is-science/wiki

**Comment by ikayz** [comment]
@yochannah I have added to the header.

**Comment by yochannah** [comment]
@ikayz I think some closing tags might be missing or something for the svg - two of the links are missing when I run hugo serve to view the site...

**Comment by ikayz** [comment]
@yochannah which icon is displaying, I look into the issue?

**Comment by yochannah** [comment]
This is what I see:

image

(you can compare to [codeisscience.com](http://www.codeisscience.com))

**Comment by ikayz** [comment]
I'll work on it and see what's causing that error.

**Comment by ikayz** [comment]
@yochannah I have added the icons, they are now working. Refer to journal_table.html

**Comment by ikayz** [comment]
image

**Comment by ikayz** [comment]
image

**Comment by ikayz** [comment]
@yochannah Icons have been added in two places, header.html and journal_table.html, I have moved some of the styles for journal_table to inline style. Please review and let me know for any further changes.

**Comment by JPTIZ** [comment]
This PR is now almost 2y old. @ikayz do you think it still apply?

**Comment by ikayz** [comment]
It won't apply since we are changing things now.

**Comment by JPTIZ** [comment]
Okay. In that case I'll be closing it and look forward to the new changes :)

**Pull request closed without merging**
