### PR TITLE
Issue/contact us

### PR DESCRIPTION
**Pull request by alokpant**
Fixes #
https://github.com/yochannah/code-is-science/issues/42

### Changes

Summary of changes you made.

* Make contact us Links adapt to smaller screens
* Fix menu items for smaller and medium devices
* Add proper two column layout to pages

### Test plan

Explain how to test changes you made.

* http://www.codeisscience.com/contact/
* Reduce size of browser to see how it appears on mobile

### Demo (optional)

**Desktop:**
image

---- 

**Mobile**
image

----

image

### CODE REVIEW

**Comment by alokpant** [comment]
Looks like now there Journal page and other pages do not have similar Header.

Isn't it possible to make Journal page also import partial than having static html in all pages? Pages include:
- add-journal.html
- journal_table.html
- mocks/add-journal.html

and so on...

**Comment by yochannah** [comment]
you're right, it would be a lot more sane to have the journal pages import the headers and footers - one of the pages you listed there is a mockup so doesn't need to be altered at this point in time but the other would. I'll make a ticket for that :D

**Comment by yochannah** [comment]
Your previews look great - just checking it out to confirm on my machine now

**Comment by yochannah** [comment]
Tested and works nicely in ff and chrome! 👍

**Comment by yochannah** [comment]
PS - email me your postal address if you'd like some stickers as thanks!

**Pull request merged**
