### PR TITLE
links added to the footer

### PR DESCRIPTION
**Pull request by suleka96**

### CODE REVIEW

**Comment by stain88** [comment]
Shouldn't the footer partial be updated here, instead of the built docs page? File in question: [footer.html](https://github.com/yochannah/code-is-science/blob/master/themes/codeisscience/layouts/partials/footer.html)
That way, it will populate to all pages that use the footer, e.g. the contact page too.

**Comment by suleka96** [comment]
Oh yes, I'm very sorry, I'm fairly new to this. I'll change it.

**Comment by yochannah** [comment]
@suleka96 have you had a chance to look at this yet? No worries if you're still working on it! :)

**Comment by yochannah** [comment]
closing due to inactivity

**Pull request closed without merging**
