### PR TITLE
R googlesheets db implementation

### PR DESCRIPTION
**Pull request by ha0ye**
Ok, I added some files to try and get at issue #5.

Here's what's going on:
* the `R` folder contains an R script and an Rmd file
* the R script renders the Rmd file into the final html file and moves it into the `static` folder (I believe this is the desired destination for it to show up in the Hugo website (eventual URL = `www.codeisscience.com/journal_table.html`)
* the Rmd file is the template for the html file, and loads several packages to retrieve the data from google sheets, clean it (namely process the dates), and produce the html widget for the interactive table

Some next steps:
* check the filenames and edit accordingly
* publish the original google sheet to the web and update the key in the Rmd file (which currently points towards a copy of the google sheet on my account that I've published to get the API to work)
* when CI is setup, add the call to run the R script, and make sure the container image has all the necessary packages for building the html file

In the meantime, you can see a demo here:
https://cdn.rawgit.com/ha0ye/code-is-science/R-googlesheets-DB-implementation/static/journal_table.html

EDIT:
oh yeah, probably needs some tweaking of the formatting!

### CODE REVIEW

**Review by JJ — APPROVED** [review]
This looks basically OK since it's not changing anything that's there, but I'm new to the repo and don't feel comfortable enough for accepting it. Can someone else take a look and/or merge it?

**Review by JJ — DISMISSED** [review]
Maybe you should try and avoid uploading the .DS_Store file.

**Comment by yochannah** [comment]
yeah, we need to do a ds store purge and add to the gitignore.

**Comment by ha0ye** [comment]
@yochannah I can add an update once I get in. Would it help if I took a look at #20 next for CI?

**Comment by yochannah** [comment]
@ha0ye yes please! <3

**Comment by ha0ye** [comment]
OK, `.gitignore` already includes `.DS_Store`, so I think those files in the repo were present *before* that change. The most recent commit I pushed to this branch only removes the various `.DS_Store` files I found under various directories and subdirectories.

**Comment by yochannah** [comment]
it's probably my fault the ds stores were there, then  😂 thanks for fixing
it

**Comment by ha0ye** [comment]
@yochannah, I have a .gitignore in my home directory (`~`) with `.DS_Store`, which solves the problem of having to add it to the .gitignore for every project.

**Comment by yochannah** [comment]
I had totally forgotten that was a thing! Thanks for the tip.

**Comment by yochannah** [comment]
... done! hopefully I'll stop accidentally dirtying repos from here on :D

**Comment by yochannah** [comment]
@ha0ye I am trying to review this PR, but I'm too n00b to R to know how to run the script. Can you give me some pointers?

**Comment by ha0ye** [comment]
@yochannah discuss in gitter?

**Comment by yochannah** [comment]
Ok, reviewed and looks good!

**Pull request merged**
