### PR TITLE
Post commit hook to run hugo automatically.

### PR DESCRIPTION
**Pull request by JJ**
Goes to #20, don't know if this is what you had in mind. Feel free to review, add or eliminate.

### CODE REVIEW

**Comment by yochannah** [comment]
Nice! I'll review after the demo call in a minute :)

**Comment by yochannah** [comment]
@JJ omg, loving the best practices page!!

**Comment by JJ** [comment]
It's just a draft... And for some reason, it wasn't generated by Hugo
locally. I might have done something wrong...

**Comment by yochannah** [comment]
I've just enabled travis for this repo, maybe that was needed...

**Comment by yochannah** [comment]
hmmmm, I triggered a build and it failed: https://travis-ci.com/yochannah/code-is-science thoughts?

**Comment by stain88** [comment]
Could it be failing because there's no `.travis.yml` file in the repo?

**Comment by yochannah** [comment]
@stain88 I think you might be right. Do you know what to change to fix this, by any chance?

**Comment by stain88** [comment]
None whatsoever, I'm afraid. Haven't used travis before.
Could always start by creating an empty file, and see what happens 😅

**Comment by JJ** [comment]
You will probably need to install Hugo in travis. Except if you want to
deploy directly from travis to some place different from github, I don't
really think it's worth the while.

**Comment by yochannah** [comment]
it's deploying to github and hosted on github pages - does that help?

**Comment by JJ** [comment]
Then you don't need to do anything in Travis. Just install the hook (it's
in a comment in the script itself), and it will regenerate pages for you as
soon as you've commited the source. Then commit again for the generated
pages, and you're done.

**Comment by yochannah** [comment]
I see! It took a while for me to understand what was happening here. Thank you!

It might be nice to automatically commit and deploy the built site, though. Will continue this in #20

**Pull request merged**
