### PR TITLE
Add GitHub Action to build table

### PR DESCRIPTION
**Pull request by rgaiacs**

### CODE REVIEW

**Comment by rgaiacs** [comment]
@JPTIZ can you review this one? Need to add https://github.com/marketplace/actions/add-commit.

**Review by JPTIZ — APPROVED** [review]
Seems to be right, just wondering if the action will just run after merge.

**Comment by JPTIZ** [comment]
Also, is it still a WIP? Or may I merge it?

**Comment by rgaiacs** [comment]
@yochannah I'm having troubles with the workflow that you use for the journal table.

Screenshot from 2020-09-03 12-37-33

I have the R output but the table isn't display. I believe that I remove something that I should not have.

**Comment by rgaiacs** [comment]
@JPTIZ I'm happy with it now.

**Review by JPTIZ — APPROVED** [review]

**Comment by JPTIZ** [comment]
Thanks a lot for your contribution :)

**Pull request merged**
